# Docker Compose para Kopi Challenge Debate API
# Configuración para desarrollo y producción

version: '3.8'

services:
  # Servicio principal de la API
  debate-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: debate-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG_MODE=false
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - ENABLE_LOGGING=true
      - MAX_CONVERSATION_HISTORY=5
      - RESPONSE_TIMEOUT_SECONDS=30
      - DEFAULT_PERSONALITY=conspiracy_theorist
    volumes:
      - ./logs:/app/logs  # Para logs persistentes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - debate-network
    labels:
      - "com.kopiachallenge.service=debate-api"
      - "com.kopiachallenge.environment=production"

  # Servicio para métricas y monitoreo (opcional, para futura extensión)
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: debate-prometheus
  #   restart: unless-stopped
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - debate-network
  #   depends_on:
  #     - debate-api

volumes:
  # Volumen para logs persistentes
  logs:
    driver: local

networks:
  # Red interna para comunicación entre servicios
  debate-network:
    driver: bridge
    labels:
      - "com.kopiachallenge.network=internal"

# Configuración adicional
x-common-variables: &common-variables
  MAX_CONVERSATION_HISTORY: 5
  RESPONSE_TIMEOUT_SECONDS: 30
  DEFAULT_PERSONALITY: conspiracy_theorist
  ENABLE_LOGGING: true
